import os

EPOSLOVANJE_BASE_URL = os.environ["EPOSLOVANJE_BASE_URL"]
EPOSLOVANJE_API_KEY = os.environ["EPOSLOVANJE_API_KEY"]

PONDI_BASE_URL = os.environ["PONDI_BASE_URL"]
PONDI_API_KEY = os.environ["PONDI_API_KEY"]
